### ISSUE TITLE
VM_INFORMATION struct

### ISSUE THREAD

**Issue by esoterix** [BreakingMalwareResearch/CFGExceptions#1]
I recommend you take a look at RtlpGuardGrantSuppressedCallAccess inside the 64 bit ntdll.dll, it indicates that your struct is incorrect. It should be 24 bytes for 64 bit.

**Comment by talliberman** [comment]
Hi esoterix,

Yes, I've seen that that is the case for the 64 bit version, but this project was meant for the x86 (or WOW) version. If you take a look at the WOW version of ntdll!RtlpGuardGrantSuppressedCallAccess you'll see that it's 0x10 bytes. This does add up because there are 2 addresses in the struct (pdwOutput, ptOffsets), whose size should increase by 4 each on x64 platforms giving us a total of 0x10 + (2 \* 4) = 0x18 which is exactly the 24 bytes you were referring to. 

There is, however, a need to change PVOID dwMustBeZero to DWORD dwMustBeZero, so that it will stay 4 bytes on 64 bit platforms as well.
